servers:
  mail:
    config: 'mail.json'
    port: 465
    run-script: '/home/mail/run'
  web:
    config: 'web.json'
    port: 80
    run-script: '/home/web/run'
  database:
    config: 'db.json'
    port: 8123
    run-script: '/home/db/run'
